# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub

# Python configuration
python:
  version: "3.9"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

# Submodules configuration
submodules:
  include: []
  recursive: false

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_build:
      - echo "Documentation build completed"
